redis:
  extends:
    file: docker-compose-common.yml
    service: redis

restaurantscommandside:
  extends:
    file: docker-compose-common.yml
    service: restaurantscommandside
  volumes:
    - ./restaurants-command-side-service/build/libs:/app
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}

restaurantsqueryside:
  extends:
    file: docker-compose-common.yml
    service: restaurantsqueryside
  volumes:
    - ./restaurants-query-side-service/build/libs:/app
  links:
    - redis
  environment:
    EVENTUATE_API_KEY_ID: ${EVENTUATE_API_KEY_ID}
    EVENTUATE_API_KEY_SECRET: ${EVENTUATE_API_KEY_SECRET}